#!/usr/bin/env node

let ru_ua = require('./lib')

let prev = ''
process.stdin.on('data', data => {
    for (let ch of data.toString()) {
	process.stdout.write(ru_ua.subst(ch, prev))
	prev = ch
    }
})
